name: first workflow

on: 
  workflow_dipatch:


jobs:
  first_job:
    name: simple job execution
    runs-on: ubuntu-latest
    steps: 
      -name: Execution of the step 1
       id: Step1ID
       run: echo "Step 1 execution"
      -name: Execution of step 2
       id: Step2ID
       shell: python
       run: echo "Step running in python shell"
       run: |
            x=4
            print(x**4)
